// 异常捕获机制
/*
try{ 
  可能出现的代码块
}catch(error){ 
  出错之后执行的代码块
} finally {
  不管有没有出错都执行的代码块
}

throw new Error("主动抛出异常");
*/
